on:
  push:
    tags:
      - 'v*'

name: Release new version

jobs:
  build:
    name: Release new version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          release: ${{ github.ref }}
          artifacts: 'suite.ndjson'
          artifactContentType: application/x-ndjson
          body: 'See suite.ndjson for the compiled test suite.'
